- name: Create build directory
  file:
    path: /tmp/build
    state: directory

- name: Create artifact directory
  file:
    path: "{{ artifact_dir }}"
    state: directory

- name: Copy app source
  copy:
    src: "{{ app_src }}/"
    dest: /tmp/build/

- name: Build WAR
  command: mvn clean package
  args:
    chdir: /tmp/build/
- name: List the build file
  command: ls -l /tmp/build/target/
  
- name: Store WAR locally
  copy:
    src: "/tmp/build/target/{{ app_name }}-v0.1.war"
    dest: "{{ artifact_dir }}/{{ app_name }}.war"
    remote_src: yes
