[build]
localhost ansible_connection=local

[dev]
dev-web ansible_host=52.90.211.30 ansible_user=ubuntu

; [prod]
; prod-web1 ansible_host=52.90.211.31 ansible_user=ubuntu
; prod-web2 ansible_host=52.90.211.32 ansible_user=ubuntu

; [web:children]
; dev
; prod