[build]
localhost ansible_connection=local

[dev]
dev-web ansible_host=192.168.1.20 ansible_user=ubuntu

[prod]
prod-web1 ansible_host=192.168.1.30 ansible_user=ubuntu
prod-web2 ansible_host=192.168.1.31 ansible_user=ubuntu

[web:children]
dev
prod