- hosts: build
  gather_facts: no
  roles:
    - mvn_build

- hosts: "{{ target_env | default('dev') }}"
  vars_files:
    - "group_vars/{{ target_env | default('dev') }}.yml"

  roles:
    - tomcat_deploy
